---
  - hosts: all
    become: true

    vars:
      app_tier:
        - "{% for instance in morpheus['instance']['apps'][0]['instances'] if 'App01' in instance.displayName %}{{ instance['container']['internalIp'] }}{% endfor %}"
      db_tier: "{% for instance in morpheus['instance']['apps'][0]['instances'] if 'DB' in instance.displayName %}{{ instance['container']['internalIp'] }}{% endfor %}"

    tasks:

      - name: Variable Test
        debug:
          msg: "{{ app_tier }}"
        ignore_errors: true
      - name: Variable Test 2
        debug:
          msg: "{{ db_tier }}"
        ignore_errors: true

      # - name: Dump Morpheus Dict Full
      #   debug:
      #     msg: "{{ morpheus }}"
      #   ignore_errors: true
      # - name: Dump Morpheus Dict Instance
      #   debug:
      #     msg: "{{ morpheus['instance'] }}"
      #   ignore_errors: true

      # - name: Dump Morpheus Main Container
      #   debug:
      #     msg: "{{ morpheus['instance']['apps'][0]['instances'][0]['container']['internalIp'] }}"
      #   ignore_errors: true
      # - name: Dump Morpheus Main Container 2
      #   debug:
      #     msg: "{{ morpheus['instance']['apps'][0]['instances'][0]['containers'][0]['server']['internalIp'] }}"
      #   ignore_errors: true

      # - name: Dump Morpheus Filter DB
      #   debug:
      #     msg: "{% for instance in morpheus['instance']['apps'][0]['instances'] if 'DB' in instance.displayName %}{{ instance['container']['internalIp'] }}{% endfor %}"
      #   ignore_errors: true

      # - name: Dump Morpheus Filter App
      #   debug:
      #     msg: "{% for instance in morpheus['instance']['apps'][0]['instances'] if 'App' in instance.displayName %}{{ instance['container']['internalIp'] }}{% endfor %}"
      #   ignore_errors: true

      # - name: Dump Morpheus Filter Web
      #   debug:
      #     msg: "{% for instance in morpheus['instance']['apps'][0]['instances'] if 'Web' in instance.displayName %}{{ instance['container']['internalIp'] }}{% endfor %}"
      #   ignore_errors: true